TRAIN_TFRECORD = 'assets/data/train.tfrecord'
TRAIN_TFRECORD_FILEPATTERN = TRAIN_TFRECORD + '*'
STATS_PATH = "assets/statistics"
SAVE_DIR = "assets/models/ddsp-solo-instrument"
GIN_BUCKET_NAME = "ddsp-gin-files"
AUDIO_BUCKET_NAME = "ddsp-audio-renders"
TAG = "viola"
AUDIO_INPUT = './assets/audioIn'
AUDIO_OUTPUT = './assets/audioOut'